# Initialize antigen with oh-my-zsh
source $HOME/.files/zsh.d/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=()
antigen bundle lukechilds/zsh-nvm

antigen theme robbyrussell

antigen apply
