# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSHDIR="$HOME/.files/zsh.d"
source $ZSHDIR/git-aliases.sh
source $ZSHDIR/aliases.sh
# TODO: I shouldn't be so Mac specific
# [[ -r $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] &&
#   source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# [[ -r $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] &&
#   source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though  oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export HISTSIZE=10000

# Documentation for zsh options:
# https://zsh.sourceforge.io/Doc/Release/Options.html#index-ALWAYS_005fTO_005fEND

# No
setopt nosharehistory
setopt no_nomatch

# Yes
setopt always_to_end
setopt auto_cd
setopt auto_pushd
setopt emacs
setopt extended_history
setopt noflowcontrol
setopt histexpiredupsfirst
setopt histignoredups
setopt histignorespace
setopt histverify
setopt inc_append_history # Use fc -RI if you want to manually import commands from history
setopt longlistjobs
setopt pushdignoredups
setopt pushdminus
setopt interactive_comments
unsetopt extendedglob

# Allow smallcase to match capital letters
# lower upper upper lower allow either lowercase or uppercase to match
# ':+l:|=* r:|=*' allow matching on both sides of the current word
zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
autoload -Uz compinit && compinit

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

export LESS=eFRX
