# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.files/zsh.d/p10k.zsh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  if [[ -f /usr/bin/nvim ]]; then
    export EDITOR='nvim'
  else
    export EDITOR='vim'
  fi
fi

ZSHDIR="$HOME/.files/zsh.d"
[[ -r $ZSHDIR/Repos/znap/znap.zsh ]] ||
  git clone --depth 1 -- \
    https://github.com/marlonrichert/zsh-snap.git $ZSHDIR/Repos/znap
source $ZSHDIR/Repos/znap/znap.zsh
zstyle ':znap:*' repos-dir $ZSHDIR/Repos

# Set all shell options BEFORE loading plugins
setopt emacs                    # use emacs keybindings
setopt no_nomatch               # avoid zsh: no matches found: foo
setopt longlistjobs             # list jobs with PIDs
setopt pushdignoredups          # don't push duplicates to the directory stack
setopt pushdminus               # flip the meaning of + and - when using pushd/popd
setopt interactive_comments     # Allow comments even in interactive shells
setopt extendedglob             # enable extended globbing, which means we can use things like **/*.txt
setopt nocaseglob               # case-insensitive globbing

znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting

# Configure zsh-autocomplete behavior (before loading plugin)
zstyle ':autocomplete:*complete*:*' insert-unambiguous yes
zstyle ':autocomplete:*history*:*' insert-unambiguous yes
zstyle ':autocomplete:menu-search:*' insert-unambiguous yes

znap source marlonrichert/zsh-autocomplete

# Configure tab to cycle through completions instead of auto-inserting
bindkey '\t' menu-complete
bindkey "$terminfo[kcbt]" reverse-menu-complete
bindkey -M menuselect '\t' menu-complete
bindkey -M menuselect "$terminfo[kcbt]" reverse-menu-complete
bindkey -M menuselect '\r' .accept-line
# Make left/right arrows exit menu and allow line editing
bindkey -M menuselect '^[[D' .accept-line  # Left arrow
bindkey -M menuselect '^[[C' .accept-line  # Right arrow

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though  oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Documentation for zsh options:
# https://zsh.sourceforge.io/Doc/Release/Options.html#index-ALWAYS_005fTO_005fEND
# Also see `man zshoptions`

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=500000
export HISTFILESIZE=1000000

# variables
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
WORDCHARS=${${${WORDCHARS:s#/#}:s,#,}:s,_,} # allow /, #, and _ in words

# history
source $ZSHDIR/history.zsh

# completion
source $ZSHDIR/completion.zsh

# directories
source $ZSHDIR/directories.zsh

# git
source "$ZSHDIR/git-aliases.sh"

export LESS=eFRX

zstyle ':completion:*' completer _complete _expand _complete:-fuzzy _correct _approximate _ignored

# Load powerlevel10k theme
source ~/.files/powerlevel10k/powerlevel10k.zsh-theme

# Load p10k configuration with fallback
# Use local machine-specific config if it exists, otherwise use portable default
if [[ -f ~/.p10k.zsh ]]; then
  source ~/.p10k.zsh
elif [[ -f ~/.files/zsh.d/p10k.zsh ]]; then
  source ~/.files/zsh.d/p10k.zsh
fi
