set nocompatible

filetype off
syntax off



" Global Vim settings

let s:mainfile = '~/.files/vim.d/main.vim'
if filereadable(expand(s:mainfile))
  exec "source " . s:mainfile
endif



" NOTE: Added because `source vimrc` doesn't turn it back on

filetype plugin indent on
syntax enable



" Vim distribution-specific settings

if exists('$TMUX')
  set ttymouse=xterm2
endif

set autoindent backspace=indent,eol,start
set autoread
set background=dark " dark | light "
set belloff=all
set complete-=i
set cscopeverbose
set display+=lastline
set encoding=utf-8
set fillchars="vert:|,fold: ,sep:|"
set formatoptions=tcqj
if &history < 1000
  set history=10000
endif
set hlsearch incsearch
set langnoremap
set nolangremap
set laststatus=2
set lazyredraw
set listchars="tab:> ,trail:-,nbsp:+"
set nobackup
set nogdefault
set noshowmatch
set nrformats="bin,hex"
set ruler
set shortmess="filnxtToOF"
set sessionoptions-=options "   unix,slash
set showcmd
set showmode
set smarttab
set startofline
set synmaxcol=3000
if &tabpagemax < 50
  set tabpagemax=50
endif
set tags="./tags;,tags"
set ttimeoutlen=50
set ttyfast
set viewoptions+="unix,slash"
set viminfo^=!
set wildmenu wildignore+=*/tmp/* "" wildmode=list:longest,full
set wildoptions="pum,tagfile"
set wrap



" Global indentation characters



" Vim directories for backup, swap, and undo

set backupdir=~/.files/vim.d/tmp/backup//
set directory=~/.files/vim.d/tmp/swap//
set undodir=~/.files/vim.d/tmp/undo//

if !isdirectory(expand(&undodir))
  call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
  call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
  call mkdir(expand(&directory), "p")
endif



runtime ftplugin/matchit.vim " Vim Built-in Plugins
runtime ftplugin/matchit.vim " Vim Built-in Plugins



" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
      \ | wincmd p | diffthis endif
endif
