#!/usr/bin/env ruby
# frozen_string_literal: true

file = "~/.gitshots/#{Time.now.to_i}.jpg"
_local_ref, local_oid, _remote_ref, remote_oid = %x{
while read local_ref local_oid remote_ref remote_oid
do
   echo $local_ref
   echo $local_oid
   echo $remote_ref
   echo $remote_oid
done
}.split

zero = %x(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0'`)
unless local_oid == zero && remote_oid == local_oid
  puts "Taking capture into #{file}"
  system "imagesnap -q -w 3 #{file} &"
end
